kind: pipeline
type: exec
name: default
platform:
  os: linux
  arch: amd64
  
steps:
  - name: build
    commands:
      - docker build --build-arg API_URL=api.mybudget.home.arpa --platform linux/amd64 -f dockerfile -t docker-registry.home.arpa/mybudget/budgetfront:latest .
    when:
      branch: main
      event:
        - pull_request
        - push

  - name: push
    commands:
      - docker push docker-registry.home.arpa/mybudget/budgetfront:latest
    when:
      branch: main
      event:
        - push